server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{service=~"socket-server|challenge-server"}'
          stages:
            - json:
                expressions:
                  level: level
                  logger_message: message
                  logger_timestamp: timestamp
            - timestamp:
                source: logger_timestamp
                format: RFC3339Nano
                action_on_failure: skip
            - labels:
                level:
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project_workdir']
        target_label: project_workdir
