global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: blert-socket-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - socket-server:3003
  - job_name: blert-challenge-server
    metrics_path: /metrics
    static_configs:
      - targets:
          - challenge-server:3003
  - job_name: blert-web
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - host.docker.internal:3000
